language: lua

# Only master is affected
branches:
  only:
  - master
  - travis_test

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install lua5.2

script:
  - lua ./tests/runall_tests.lua

after_success:
  - echo "The job was a success"

notifications:
  email:
    on_success: change
    on_failure: always