# Only master is affected
language: lua

branches:
  only:
  - master
  - travis_test

# Running builds in parallel for lua 5.2 and 5.3
env:
- LUA=5.2
- LUA=5.3

before_install:
  - sudo apt-get update
  - sudo export LUA_VERSION=$LUA

install:
  - sudo echo "Lua version: $LUA_VERSION"
  - sudo apt-get install $LUA_VERSION

script:
  - lua ./tests/runall_tests.lua

after_success:
  - echo "Wirebait job was a success!"

notifications:
  email:
    on_success: change
    on_failure: always